name: Run tests
on:
  pull_request:
    paths:
      - .github/**
      - point_seg/**
      - tests.py
      - create_tfrecords.py
      - train_shapenet_core.py
      - requirements.txt
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install wandb
          pip install -r requirements.docker
          pytest tests.py -s