name: Run tests
on:
  pull_request:
    paths:
      - .github/**
      - point_seg/**
      - tests.py
      - requirements.txt
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://tensorflow/tensorflow
      - run: |
          pip install -U pip
          pip install -r requirements.docker
          pytest tests.py -s